version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: AutooR_postgres
    environment:
      POSTGRES_DB: AutooR_db
      POSTGRES_USER: AutooR_user
      POSTGRES_PASSWORD: Vekil4023.
      POSTGRES_HOST_AUTH_METHOD: md5
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped
    networks:
      - AutooR_network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: AutooR_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@AutooR.de
      PGADMIN_DEFAULT_PASSWORD: Vekil4023.
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "8080:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres
    restart: unless-stopped
    networks:
      - AutooR_network

volumes:
  postgres_data:
  pgadmin_data:

networks:
  AutooR_network:
    driver: bridge
